#define TAPPING_TERM 200
#define MOUSEKEY_DELAY 10
#define MOUSEKEY_INTERVAL 30
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_TIME_TO_MAX 10
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40
